name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  bidi: ^2.0.9
  charset_converter: ^2.1.1
  enough_convert: ^1.6.0
  flutter:
    sdk: flutter
  gbk_codec: ^0.4.0
  hex: ^0.2.0
  image: ^4.0.17
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
