name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.0.3
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  charset_converter: ^1.0.3
  esc_pos_utils:
    git:
      url: git://github.com/Maged12/esc_pos_utils.git
      ref: master
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
